---
# .pre-commit-config.yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.3
    hooks:
      - id: ruff
        args: [--fix]
  - repo: https://github.com/lyz-code/yamlfix
    rev: 1.17.0
    hooks:
      - id: yamlfix
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args: [--config-file=mypy.ini]
        # test
#        additional_dependencies: [pyqt6>=6.7.1]
#  - repo: https://github.com/google/pytype
#    rev: 2024.04.11
#    hooks:
#      - id: pytype
#        entry: sh -c 'command -v pytype > /dev/null 2>&1 && pytype || echo "pytype
#          is not installed, skipping check"'
#        default_install_hook_types: [local]
#  - repo: https://github.com/pre-commit/pre-commit-hooks
#    rev: v4.6.0
#    hooks:
#      - id: trailing-whitespace
#      - id: end-of-file-fixer
#      - id: check-yaml
#        args: ['--allow-multiple-docs']
#      - id: debug-statements

#  - repo: https://github.com/psf/black
#    rev: 24.8.0
#    hooks:
#      - id: black
#        language_version: python3

#  - repo: https://github.com/pre-commit/pre-commit-hooks
#    rev: v4.6.0
#    hooks:
#      - id: check-added-large-files

#  - repo: https://github.com/pycqa/flake8
#    rev: 7.1.1
#    hooks:
#      - id: flake8

#  - repo: https://github.com/pycqa/isort
#    rev: v5.11.2
#    hooks:
#      - id: isort
