---
name: Create Release
on:
  workflow_dispatch:
jobs:
  find_some_body:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
    outputs:
      final_release_body: ${{ steps.compare.outputs.final_release_body }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get latest release with body
        id: get_latest_release_with_body
        run: |
          releases=$(gh release list --limit 100 --json tagName --jq '.[] | select(.tagName != null) | .tagName')
          for tag in $releases; do
            body=$(gh release view "$tag" --json body -q '.body')
            if [ -n "$body" ]; then
              break
            fi
          done
          echo "latest_release_body=$body" >> $GITHUB_ENV
      - name: Compare release notes
        id: compare
        run: |-
          current_release_body=$(cat Release_changes.md)
          if [ "$current_release_body" == "${{ env.latest_release_body }}" ]; then
            echo "final_release_body=" >> $GITHUB_OUTPUT
          else
            echo "final_release_body=$current_release_body" >> $GITHUB_OUTPUT
          fi
  create_release:
    runs-on: ubuntu-latest
    needs: find_some_body
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || sudo apt install curl -y
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y
      - name: Download Windows App
        run: gh run download --repo ${{ github.repository }} --name Apps-Purchases-Windows
          --dir ./dist/Apps-Purchases-windows-latest
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Download Linux App
        run: gh run download --repo ${{ github.repository }} --name Apps-Purchases-Ubuntu
          --dir ./dist/Apps-Purchases-ubuntu-latest
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Download macOS App
        run: gh run download --repo ${{ github.repository }} --name Apps-Purchases-macOS
          --dir ./dist/Apps-Purchases-macos-latest
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Copy orders directory
        run: |
          cp -r ./orders ./dist/Apps-Purchases-windows-latest/
          cp -r ./orders ./dist/Apps-Purchases-ubuntu-latest/
          cp -r ./orders ./dist/Apps-Purchases-macos-latest/
      - name: Create Archives
        run: |
          cd ./dist
          zip -r Apps-Purchases-windows-latest.zip Apps-Purchases-windows-latest
          zip -r Apps-Purchases-ubuntu-latest.zip Apps-Purchases-ubuntu-latest
          zip -r Apps-Purchases-macos-latest.zip Apps-Purchases-macos-latest
      - name: Set current date
        id: set_current_date
        run: echo "current_date=$(date +v%Y.%m.%d.%H.%M.%S)" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ env.current_date }}
          name: Release ${{ env.current_date }}
          body: ${{ needs.find_some_body.outputs.final_release_body }}
          draft: false
          prerelease: false
          files: |-
            ./dist/Apps-Purchases-windows-latest.zip
            ./dist/Apps-Purchases-ubuntu-latest.zip
            ./dist/Apps-Purchases-macos-latest.zip
