---
name: Create Release
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: Release tag name
        required: true
      release_name:
        description: Release name
        required: true
      release_body:
        description: Release description
        required: false
jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: ${{ github.event.inputs.release_name }}
          body: ${{ github.event.inputs.release_body }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload Linux artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/linux/БФТ-Закупки
          asset_name: БФТ-Закупки-linux(ubuntu)
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload macOS artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/macos/БФТ-Закупки
          asset_name: БФТ-Закупки-macOS
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload Windows artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/windows/БФТ-Закупки
          asset_name: БФТ-Закупки-Windows
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ github.token }}
