---
name: Create Release
on:
  workflow_dispatch:
jobs:
  create_release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || sudo apt install curl -y
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y
      - name: Download Windows App
        run: gh run download --repo ${{ github.repository }} --name Apps-Purchases-windows-latest
          --dir ./dist/windows-latest
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Download Linux App
        run: gh run download --repo ${{ github.repository }} --name Apps-Purchases-ubuntu-latest
          --dir ./dist/ubuntu-latest
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Download macOS App
        run: gh run download --repo ${{ github.repository }} --name Apps-Purchases-macos-latest
          --dir ./dist/macos-latest
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Set current date
        id: set_current_date
        run: echo "current_date=$(date +v%Y.%m.%d.%H.%M.%S)" >> $GITHUB_OUTPUT
      - name: Check Body
        run: |
          echo "body path:"
          echo "${{ steps.compare_release.outputs.body_path }}"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ steps.set_current_date.outputs.current_date }}
          release_name: ${{ steps.set_current_date.outputs.current_date }}
          body_path: ${{ steps.compare_release.outputs.body_path }}
          draft: false
          prerelease: false
      - name: Upload Windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/windows-latest/Apps-Purchases.exe
          asset_name: Apps-Purchases-Windows.exe
          asset_content_type: application/octet-stream
      - name: Upload macOS artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/macos-latest/Apps-Purchases
          asset_name: Apps-Purchases-macOS
          asset_content_type: application/octet-stream
      - name: Upload Linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/ubuntu-latest/Apps-Purchases
          asset_name: Apps-Purchases-ubuntu
          asset_content_type: application/octet-stream
  compare_release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
    outputs:
      body_path: ${{ steps.compare.outputs.body_path }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get latest release with body
        id: get_latest_release_with_body
        run: |
          releases=$(gh release list --limit 100 --json tagName --jq '.[] | select(.tagName != null) | .tagName')
          for tag in $releases; do
            body=$(gh release view "$tag" --json body -q '.body')
            if [ -n "$body" ]; then
              echo "$body"
              break
            fi
          done
          echo "latest_release_body=$body" >> $GITHUB_OUTPUT
      - name: Compare release notes
        id: compare
        run: |-
          current_release_body=$(cat Release_changes.md)
          latest_release_body="${{ steps.get_latest_release_with_body.outputs.latest_release_body }}"
          if [ "$current_release_body" == "$latest_release_body" ]; then
            echo "body_path=" >> $GITHUB_OUTPUT
          else
            echo "body_path=Release_changes.md" >> $GITHUB_OUTPUT
          fi
          echo "Latest release body:"
          echo "$latest_release_body"
          echo "Current release body:"
          echo "$current_release_body"
          echo "body_path:"
          echo "$body_path"
