---
name: Create Release
on:
  workflow_dispatch:
jobs:
  create_release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || sudo apt install curl -y
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y
      - name: Download Windows App
        run: gh run download --repo ${{ github.repository }} --name Apps-Purchases-windows-latest --dir ./dist/windows-latest
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Download Linux App
        run: gh run download --repo ${{ github.repository }} --name Apps-Purchases-ubuntu-latest --dir ./dist/ubuntu-latest
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Download macOS App
        run: gh run download --repo ${{ github.repository }} --name Apps-Purchases-macos-latest --dir ./dist/macos-latest
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: v${{ steps.set_current_date.outputs.current_date }}
          release_name: v${{ steps.set_current_date.outputs.current_date }}
          body_path: ${{ steps.compare_release.outputs.body_path }}
          draft: false
          prerelease: false
      - name: Upload Windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/windows-latest/Apps-Purchases.exe
          asset_name: Apps-Purchases-Windows.exe
          asset_content_type: application/octet-stream
      - name: Upload macOS artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/macos-latest/Apps-Purchases
          asset_name: Apps-Purchases-macOS
          asset_content_type: application/octet-stream
      - name: Upload Linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/ubuntu-latest/Apps-Purchases
          asset_name: Apps-Purchases-ubuntu
          asset_content_type: application/octet-stream

  set_current_date:
    runs-on: ubuntu-latest
    outputs:
      current_date: ${{ steps.date.outputs.current_date }}
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=current_date::$(date +v%Y.%m.%d.%H.%M.%S)"

  compare_release:
    runs-on: ubuntu-latest
    outputs:
      body_path: ${{ steps.compare.outputs.body_path }}
    steps:
      - name: Get latest release
        id: get_latest_release
        run: |
          latest_release=$(gh release view --json body --jq '.body')
          echo "::set-output name=latest_release::$latest_release"
      - name: Compare release notes
        id: compare
        run: |
          current_release=$(cat Release_changes.md)
          if [ "$current_release" == "${{ steps.get_latest_release.outputs.latest_release }}" ]; then
            echo "::set-output name=body_path::"
          else
            echo "::set-output name=body_path::Release_changes.md"
          fi
