---
name: Create Release
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: Release tag name (e.g., v1.0.0)
        required: true
      release_name:
        description: Release name
        required: true
      release_body:
        description: Release description
        required: false
jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: ${{ github.event.inputs.release_name }}
          body: ${{ github.event.inputs.release_body }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Apps-Purchases-ubuntu-latest
          path: ./dist/linux/
      - name: Upload Linux artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/linux/Apps-Purchases
          asset_name: Apps-Purchases-linux(ubuntu)
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Download macOS Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Apps-Purchases-macos-latest
          path: ./dist/macos/
      - name: Upload macOS artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/macos/Apps-Purchases
          asset_name: Apps-Purchases-macOS
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Download Windows Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Apps-Purchases-windows-latest
          path: ./dist/windows/
      - name: Upload Windows artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/windows/Apps-Purchases
          asset_name: Apps-Purchases-Windows
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
