---
name: Create Release
on:
  push:
    tags: [v*]
jobs:
  create_release:
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Windows App
        uses: actions/download-artifact@v4
        with:
          name: Apps-Purchases-windows-latest
          path: ./dist/
      - name: Download Linux App
        uses: actions/download-artifact@v4
        with:
          name: Apps-Purchases-ubuntu-latest
          path: ./dist/
      - name: Download macOS App
        uses: actions/download-artifact@v4
        with:
          name: Apps-Purchases-macos-latest
          path: ./dist/
      - name: List contents of current directory
        run: find . -type f -print
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${GITHUB_REF##*/}
          release_name: ${GITHUB_REF##*/}
          body: ${{ Release_changes.md }}
          draft: false
          prerelease: false
      - name: Upload Windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/Apps-Purchases-windows-latest
          asset_name: Apps-Purchases-Windows
          asset_content_type: application/octet-stream
      - name: Upload macOS artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/Apps-Purchases-macos-latest
          asset_name: Apps-Purchases-macOS
          asset_content_type: application/octet-stream
      - name: Upload Linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/Apps-Purchases-ubuntu-latest
          asset_name: Apps-Purchases-ubuntu
          asset_content_type: application/octet-stream
