---
name: Create Release
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: Release tag name (e.g., v1.0.0)
        required: true
      release_name:
        description: Release name
        required: true
      release_body:
        description: Release description
        required: false
jobs:
  create_release:
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: ${{ github.event.inputs.release_name }}
          body: ${{ github.event.inputs.release_body }}
          draft: false
          prerelease: false
      - name: Upload Windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/windows-latest/Apps-Purchases.exe
          asset_name: Apps-Purchases-Windows
          asset_content_type: application/octet-stream
      - name: Upload macOS artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/macos-latest/Apps-Purchases
          asset_name: Apps-Purchases-macOS
          asset_content_type: application/octet-stream
      - name: Upload Linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/ubuntu-latest/Apps-Purchases
          asset_name: Apps-Purchases-linux(ubuntu)
          asset_content_type: application/octet-stream
