---
name: List Artifacts
on:
  workflow_dispatch:
jobs:
  list_artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: List Artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          echo "Listing all artifacts:"
          gh api repos/${{ github.repository }}/actions/artifacts --paginate | jq -r '.artifacts[] | .name'
