---
name: Test Download Specific Artifacts with CLI
on:
  workflow_dispatch:
jobs:
  download_specific_artifacts:
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || sudo apt install curl -y
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y
      - name: Download Windows App
        run: gh run download --repo ${{ github.repository }} --name Apps-Purchases-windows-latest
          --dir ./dist/windows-latest
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Download Linux App
        run: gh run download --repo ${{ github.repository }} --name Apps-Purchases-ubuntu-latest
          --dir ./dist/ubuntu-latest
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Download macOS App
        run: gh run download --repo ${{ github.repository }} --name Apps-Purchases-macos-latest
          --dir ./dist/macos-latest
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: List contents of current directory
        run: find . -type f -print
