---
name: Download Specific Artifacts
on:
  workflow_dispatch:
jobs:
  download_specific_artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Windows App
        uses: actions/download-artifact@v4
        with:
          name: Apps-Purchases-windows-latest
          path: ./dist/
      - name: Download Linux App
        uses: actions/download-artifact@v4
        with:
          name: Apps-Purchases-ubuntu-latest
          path: ./dist/
      - name: Download macOS App
        uses: actions/download-artifact@v4
        with:
          name: Apps-Purchases-macos-latest
          path: ./dist/
      - name: List contents of current directory
        run: find . -type f -print
